#!/bin/sh

# Copyright: 2014 Francois Lafont <francois.lafont@crdp.ac-versailles.fr>
#
# License: GPL-3.0+
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

export PATH='/usr/local/bin:/usr/bin:/bin'

if ! cd '/usr/share/pyshared/iaConvert/'
then
    echo "Sorry, 'cd /usr/share/pyshared/iaConvert/' failed."
    echo "There is something wrong with the installation of image-active."
    exit 1
fi

exec python ./imageactive2.py


